Algoritmo "Aula 5 - Verificar se o numero é maior"

Var

n1, n2, resultado: inteiro

Inicio

escreval("Algoritmo para verificação se um numero é maior que outro")
escreval("Digite o primeiro numero: ")
leia(n1)
escreval("Digite o segundo numero: ")
leia(n2)
se n1 > n2 então
   escreval("O primeiro numero digitado é maior!")
   senão
   escreval("O segundo numero digitado é maior!")
fimse
Fimalgoritmo